apiVersion: v1
kind: Service
metadata:
  name: android-ota 
  labels:
    run: android-ota 
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: android-ota 
  type: LoadBalancer
